export const posts = [
    {
        id: 1,
        title: "The Intermediate Guide to Healthy Food",
        description: "snadjk snadjk snadjk snadjk snadjk snadjk snadjk snadjk snadjk snadjk snadjk",
        date: "25 April 2024",
        views: "124k Views",
        readTime: "4 mins read",
        image: "/assets/images/healthy-food.jpg", 
    },
    {
        id: 2,
        title: "The Intermediate Guide to Healthy Food",
        description: "snadjk snadjk snadjk snadjk snadjk snadjk snadjk snadjk snadjk snadjk snadjk",
        date: "25 April 2024",
        views: "124k Views",
        readTime: "4 mins read",
        image: "/assets/images/healthy-food.jpg", 
    },
    {
        id: 3,
        title: "The Intermediate Guide to Healthy Food",
        description: "snadjk snadjk snadjk snadjk snadjk snadjk snadjk snadjk snadjk snadjk snadjk",
        date: "25 April 2024",
        views: "124k Views",
        readTime: "4 mins read",
        image: "/assets/images/healthy-food.jpg", 
    },

    {
        id: 4,
        title: "The Intermediate Guide to Healthy Food",
        description: "snadjk snadjk snadjk snadjk snadjk snadjk snadjk snadjk snadjk snadjk snadjk",
        date: "25 April 2024",
        views: "124k Views",
        readTime: "4 mins read",
        image: "/assets/images/healthy-food.jpg", 
    },
    {
        id: 5,
        title: "The Intermediate Guide to Healthy Food",
        description: "snadjk snadjk snadjk snadjk snadjk snadjk snadjk snadjk snadjk snadjk snadjk",
        date: "25 April 2024",
        views: "124k Views",
        readTime: "4 mins read",
        image: "/assets/images/healthy-food.jpg", 
    },
    {
        id: 6,
        title: "The Intermediate Guide to Healthy Food",
        description: "snadjk snadjk snadjk snadjk snadjk snadjk snadjk snadjk snadjk snadjk snadjk",
        date: "25 April 2024",
        views: "124k Views",
        readTime: "4 mins read",
        image: "/assets/images/healthy-food.jpg", 
    },
];
